### ISSUE TITLE
Add support for task priorities

### ISSUE THREAD

**Issue by prabirshrestha** [ZeroAssumptions/aide-de-camp#7]
Some urgent task would need to be schedule earlier than existing one. Allowing us to pass priority as a number would allow us to enable this scenario.

**Comment by andoriyu** [comment]
@prabirshrestha Technically this is already supported, but on task type level. We are still going to add priority, this I am breaking change since public interface going to change. 

Meanwhile, to achieve this, you can create a separate [`Queue`](https://docs.rs/aide-de-camp/latest/aide_de_camp/core/queue/trait.Queue.html) that only works with your priority task types. Pair it with a new `JobRunner` and now you have a worker that only process your priority tasks. 

Additionally, you can schedule tasks in the past, "I need this done yesterday" will have the same effect on scheduling as on people.

This solution has a downside that if priority worker and regular worker run on the same machine - both have their own concurrency and no way to communicate.
